# Generated by dev-env. Rerun dev-env init to update.
{ lib, ... }:
{
  imports = [
    /home/ray/.config/devenv/ray/profiles/nix.nix
  ]
  ++ lib.optional (builtins.pathExists ./devenv.local.nix) ./devenv.local.nix;
}
