usage() {
  cat <<'EOF'
Usage:
  dev-env init [--tracked|-t] [PROFILE...]
  dev-env list

With no PROFILE, dev-env detects the project languages. Profiles can also be
passed without the "init" subcommand, for example:

  dev-env frontend go

By default, generated devenv files stay local through .git/info/exclude.
Use --tracked or -t to expose devenv.nix, devenv.yaml and devenv.lock to Git.
EOF
}

list_profiles() {
  cat <<'EOF'
frontend    Node.js and Corepack
go          Go with native go.mod toolchain selection, Delve and Task
rust        rustup and native build dependencies
zig         Zig
python      Python and uv
cpp         GCC, CMake, Ninja, ccache and GDB
lua         Lua and LuaRocks
nix         deadnix and statix
shell       ShellCheck and shfmt
docs        Typst and Typstyle
EOF
}

canonical_profile() {
  case "$1" in
    frontend | web | node | js | ts)
      printf '%s\n' frontend
      ;;
    go | golang)
      printf '%s\n' go
      ;;
    rust | rs)
      printf '%s\n' rust
      ;;
    zig)
      printf '%s\n' zig
      ;;
    python | py)
      printf '%s\n' python
      ;;
    cpp | c | cxx | c++)
      printf '%s\n' cpp
      ;;
    lua)
      printf '%s\n' lua
      ;;
    nix)
      printf '%s\n' nix
      ;;
    shell | sh | bash | fish)
      printf '%s\n' shell
      ;;
    docs | typst)
      printf '%s\n' docs
      ;;
    *)
      return 1
      ;;
  esac
}

declare -a selected_profiles=()

add_profile() {
  local profile="$1"
  local selected

  for selected in "${selected_profiles[@]}"; do
    if [[ "$selected" == "$profile" ]]; then
      return
    fi
  done

  selected_profiles+=("$profile")
}

detect_profiles() {
  if [[ -f package.json ]]; then
    add_profile frontend
  fi

  if [[ -f go.mod || -f go.work ]]; then
    add_profile go
  fi

  if [[ -f Cargo.toml || -f rust-toolchain || -f rust-toolchain.toml ]]; then
    add_profile rust
  fi

  if [[ -f build.zig || -f build.zig.zon ]]; then
    add_profile zig
  fi

  if [[ -f pyproject.toml || -f uv.lock || -f requirements.txt ]]; then
    add_profile python
  fi

  if [[ -f CMakeLists.txt || -f meson.build || -f Makefile ]] \
    || compgen -G '*.c' >/dev/null \
    || compgen -G '*.cc' >/dev/null \
    || compgen -G '*.cpp' >/dev/null; then
    add_profile cpp
  fi

  if [[ -f .luarc.json || -f init.lua || -f stylua.toml ]]; then
    add_profile lua
  fi

  if [[ -f flake.nix || -f default.nix || -f shell.nix ]]; then
    add_profile nix
  fi

  if compgen -G '*.sh' >/dev/null || compgen -G '*.fish' >/dev/null; then
    add_profile shell
  fi

  if compgen -G '*.typ' >/dev/null; then
    add_profile docs
  fi
}

add_exclude() {
  local pattern="$1"

  if ! grep --fixed-strings --line-regexp --quiet "$pattern" "$exclude_file" 2>/dev/null; then
    printf '%s\n' "$pattern" >>"$exclude_file"
  fi
}

remove_exclude() {
  local pattern="$1"
  local status
  local temporary_exclude

  temporary_exclude="$(mktemp "$(dirname "$exclude_file")/.exclude.XXXXXX")"
  if grep --fixed-strings --line-regexp --invert-match "$pattern" "$exclude_file" >"$temporary_exclude"; then
    status=0
  else
    status=$?
  fi

  if ((status > 1)); then
    rm -f "$temporary_exclude"
    return "$status"
  fi

  chmod --reference="$exclude_file" "$temporary_exclude"
  mv "$temporary_exclude" "$exclude_file"
}

case "${1:-}" in
  -h | --help | help)
    usage
    exit
    ;;
  list)
    list_profiles
    exit
    ;;
  init)
    shift
    ;;
esac

tracked=false
declare -a requested_profiles=()

for argument in "$@"; do
  case "$argument" in
    --tracked | -t)
      tracked=true
      ;;
    -h | --help)
      usage
      exit
      ;;
    -*)
      printf 'Unknown option: %s\n\n' "$argument" >&2
      usage >&2
      exit 1
      ;;
    *)
      requested_profiles+=("$argument")
      ;;
  esac
done

if ! project_root="$(git rev-parse --show-toplevel 2>/dev/null)"; then
  printf '%s\n' "dev-env must be run inside a Git worktree." >&2
  exit 1
fi

cd "$project_root"

for requested_profile in "${requested_profiles[@]}"; do
  if [[ "$requested_profile" == all ]]; then
    for profile in frontend go rust zig python cpp lua nix shell docs; do
      add_profile "$profile"
    done
    continue
  fi

  if ! profile="$(canonical_profile "$requested_profile")"; then
    printf 'Unknown profile: %s\n\n' "$requested_profile" >&2
    list_profiles >&2
    exit 1
  fi

  add_profile "$profile"
done

if ((${#selected_profiles[@]} == 0)); then
  detect_profiles
fi

if ((${#selected_profiles[@]} == 0)); then
  printf '%s\n\n' "No language profile was detected. Pass one explicitly:" >&2
  list_profiles >&2
  exit 1
fi

generated_marker="# Generated by dev-env. Rerun dev-env init to update."
devenv_nix="$project_root/devenv.nix"
devenv_yaml="$project_root/devenv.yaml"

for generated_file in "$devenv_nix" "$devenv_yaml"; do
  if [[ -e "$generated_file" ]] && [[ "$(head -n 1 "$generated_file")" != "$generated_marker" ]]; then
    printf '%s\n' "Refusing to overwrite existing $generated_file." >&2
    exit 1
  fi
done

temporary_nix="$(mktemp "$project_root/.dev-env-nix.XXXXXX")"
temporary_yaml="$(mktemp "$project_root/.dev-env-yaml.XXXXXX")"
trap 'rm -f "$temporary_nix" "$temporary_yaml"' EXIT

{
  printf '%s\n' "$generated_marker"
  printf '%s\n' '{ lib, ... }:'
  printf '%s\n' '{'
  printf '%s\n' '  imports = ['

  for profile in "${selected_profiles[@]}"; do
    printf '    (builtins.toPath "%s/profiles/%s.nix")\n' "$RAY_DEVENV_MODULE_ROOT" "$profile"
  done

  printf '%s\n' '  ] ++ lib.optional (builtins.pathExists ./devenv.local.nix) ./devenv.local.nix;'
  printf '%s\n' '}'
} >"$temporary_nix"

nixfmt "$temporary_nix"

{
  printf '%s\n' "$generated_marker"
  printf '%s\n' 'inputs:'
  printf '%s\n' '  nixpkgs:'
  printf '%s\n' '    url: github:cachix/devenv-nixpkgs/rolling'
} >"$temporary_yaml"

mv "$temporary_nix" "$devenv_nix"
mv "$temporary_yaml" "$devenv_yaml"

exclude_file="$(git rev-parse --git-path info/exclude)"
mkdir -p "$(dirname "$exclude_file")"
touch "$exclude_file"

for pattern in /devenv.local.nix /.devenv/ /.devenv.flake.nix; do
  add_exclude "$pattern"
done

for pattern in /devenv.nix /devenv.yaml /devenv.lock; do
  if [[ "$tracked" == true ]]; then
    remove_exclude "$pattern"
  else
    add_exclude "$pattern"
  fi
done

devenv allow --quiet

printf 'Configured %s with profiles: %s\n' "$project_root" "${selected_profiles[*]}"
if [[ "$tracked" == true ]]; then
  printf '%s\n' "devenv.nix, devenv.yaml and devenv.lock are visible to Git."
fi
printf '%s\n' "Run 'devenv shell' once now; future directory entries auto-activate."
