import argparse
import subprocess
from pathlib import Path

MARKER = "# Generated by dev-env. Rerun dev-env init to update."
MODULE_ROOT: Path = Path("__MODULE_ROOT__")
GIT: str = "__GIT__"
DEVENV: str = "__DEVENV__"
NIXFMT: str = "__NIXFMT__"
PRETTIER: str = "__PRETTIER__"
PROFILES: dict[str, tuple[str, tuple[str, ...]]] = {
    "config": ("JSON, YAML, TOML and web document tooling", ()),
    "container": (
        "Dockerfile and Compose tooling",
        (
            "Dockerfile",
            "Dockerfile.*",
            "Containerfile",
            "Containerfile.*",
            "compose.yaml",
            "compose.yml",
            "docker-compose.yaml",
            "docker-compose.yml",
        ),
    ),
    "frontend": ("Node.js, Corepack and frontend tooling", ("package.json",)),
    "go": ("Go, Delve, Task and editor tooling", ("go.mod", "go.work")),
    "rust": (
        "rust-overlay, native build dependencies and editor tooling",
        ("Cargo.toml", "rust-toolchain", "rust-toolchain.toml"),
    ),
    "zig": ("Zig and ZLS", ("build.zig", "build.zig.zon")),
    "python": (
        "Python, uv and editor tooling",
        ("pyproject.toml", "uv.lock", "requirements.txt"),
    ),
    "cpp": (
        "GCC, Clang tools, CMake, Ninja, ccache and GDB",
        ("CMakeLists.txt", "meson.build", "Makefile", "*.c", "*.cc", "*.cpp"),
    ),
    "lua": (
        "Lua, LuaRocks and editor tooling",
        (".luarc.json", "init.lua", "stylua.toml"),
    ),
    "nix": (
        "nixd, nixfmt, deadnix and statix",
        ("flake.nix", "default.nix", "shell.nix"),
    ),
    "shell": ("Shell language servers, ShellCheck and shfmt", ("*.sh", "*.fish")),
    "latex": ("TexLab and latexindent", ("*.tex", "*.bib")),
    "typst": ("Typst, Tinymist and Typstyle", ("*.typ",)),
}
LOCAL_EXCLUDES = ("/devenv.local.nix", "/.devenv/", "/.devenv.flake.nix")
GENERATED_EXCLUDES = ("/devenv.nix", "/devenv.yaml", "/devenv.lock")


def detect_profiles(root: Path) -> list[str]:
    return [
        name
        for name, (_, patterns) in PROFILES.items()
        if any(path.is_file() for pattern in patterns for path in root.glob(pattern))
    ]


def init(profiles: list[str], tracked: bool) -> None:
    root = Path(
        subprocess.check_output(
            [GIT, "rev-parse", "--show-toplevel"], text=True
        ).strip()
    )
    profiles = profiles or detect_profiles(root)
    if not profiles:
        raise SystemExit("No profile detected; run `dev-env list` and select one.")

    imports = "\n".join(
        f"    {MODULE_ROOT}/profiles/{profile}.nix" for profile in profiles
    )
    devenv_nix = root / "devenv.nix"
    devenv_nix.write_text(
        f"""\
{MARKER}
{{ lib, ... }}:

{{
  imports = [
{imports}
  ] ++ lib.optional (builtins.pathExists ./devenv.local.nix) ./devenv.local.nix;
}}
"""
    )

    rust_overlay = (
        """\
  rust-overlay:
    url: github:oxalica/rust-overlay
    inputs:
      nixpkgs:
        follows: nixpkgs
"""
        if "rust" in profiles
        else ""
    )
    node_overlay = (
        """\
  node-overlay:
    url: github:so1ve/node-overlay
    inputs:
      nixpkgs:
        follows: nixpkgs
"""
        if "frontend" in profiles
        else ""
    )
    devenv_yaml = root / "devenv.yaml"
    devenv_yaml.write_text(
        f"""\
{MARKER}
inputs:
  nixpkgs:
    url: github:cachix/devenv-nixpkgs/rolling
{rust_overlay}{node_overlay}"""
    )
    subprocess.run([NIXFMT, devenv_nix], check=True)
    subprocess.run([PRETTIER, "--write", devenv_yaml], check=True)

    exclude = Path(
        subprocess.check_output(
            [
                GIT,
                "rev-parse",
                "--path-format=absolute",
                "--git-path",
                "info/exclude",
            ],
            text=True,
        ).strip()
    )
    lines = exclude.read_text().splitlines() if exclude.exists() else []
    lines = list(dict.fromkeys([*lines, *LOCAL_EXCLUDES]))
    if tracked:
        lines = [line for line in lines if line not in GENERATED_EXCLUDES]
    else:
        lines = list(dict.fromkeys([*lines, *GENERATED_EXCLUDES]))
    exclude.parent.mkdir(parents=True, exist_ok=True)
    exclude.write_text("\n".join(lines) + "\n")

    subprocess.run([DEVENV, "allow", "--quiet"], check=True)
    print(f"Configured {root} with profiles: {' '.join(profiles)}")


def main() -> None:
    parser = argparse.ArgumentParser(prog="dev-env")
    commands = parser.add_subparsers(dest="command", required=True)
    init_parser = commands.add_parser("init", help="generate devenv files")
    init_parser.add_argument("-t", "--tracked", action="store_true")
    init_parser.add_argument("profiles", nargs="*", choices=PROFILES, metavar="PROFILE")
    commands.add_parser("list", help="list profiles")
    args = parser.parse_args()

    if args.command == "list":
        width = max(map(len, PROFILES))
        print(
            "\n".join(
                f"{name:<{width}}  {description}"
                for name, (description, _) in PROFILES.items()
            )
        )
    else:
        init(args.profiles, args.tracked)


if __name__ == "__main__":
    main()
