import argparse
import os
import subprocess
from pathlib import Path

MARKER = "# Generated by dev-env. Rerun dev-env init to update."
PROFILES: dict[str, tuple[str, tuple[str, ...]]] = {
    "frontend": ("Node.js and Corepack", ("package.json",)),
    "go": ("Go, Delve and Task", ("go.mod", "go.work")),
    "rust": (
        "rust-overlay and native build dependencies",
        ("Cargo.toml", "rust-toolchain", "rust-toolchain.toml"),
    ),
    "zig": ("Zig", ("build.zig", "build.zig.zon")),
    "python": ("Python and uv", ("pyproject.toml", "uv.lock", "requirements.txt")),
    "cpp": (
        "GCC, CMake, Ninja, ccache and GDB",
        ("CMakeLists.txt", "meson.build", "Makefile", "*.c", "*.cc", "*.cpp"),
    ),
    "lua": ("Lua and LuaRocks", (".luarc.json", "init.lua", "stylua.toml")),
    "nix": ("deadnix and statix", ("flake.nix", "default.nix", "shell.nix")),
    "shell": ("ShellCheck and shfmt", ("*.sh", "*.fish")),
    "typst": ("Typst and Typstyle", ("*.typ",)),
}
LOCAL_EXCLUDES = ("/devenv.local.nix", "/.devenv/", "/.devenv.flake.nix")
GENERATED_EXCLUDES = ("/devenv.nix", "/devenv.yaml", "/devenv.lock")


def detect_profiles(root: Path) -> list[str]:
    return [
        name
        for name, (_, patterns) in PROFILES.items()
        if any(path.is_file() for pattern in patterns for path in root.glob(pattern))
    ]


def render_nix(module_root: Path, profiles: list[str]) -> str:
    imports = "\n".join(
        f"    {module_root}/profiles/{profile}.nix" for profile in profiles
    )
    return f"""\
{MARKER}
{{ lib, ... }}:

{{
  imports = [
{imports}
  ] ++ lib.optional (builtins.pathExists ./devenv.local.nix) ./devenv.local.nix;
}}
"""


def render_yaml(profiles: list[str]) -> str:
    rust_overlay = (
        """\
  rust-overlay:
    url: github:oxalica/rust-overlay
    inputs:
      nixpkgs:
        follows: nixpkgs
"""
        if "rust" in profiles
        else ""
    )
    return f"""\
{MARKER}
inputs:
  nixpkgs:
    url: github:cachix/devenv-nixpkgs/rolling
{rust_overlay}"""


def update_excludes(root: Path, tracked: bool) -> None:
    path = Path(
        subprocess.check_output(
            ["git", "rev-parse", "--git-path", "info/exclude"], text=True
        ).strip()
    )
    path = path if path.is_absolute() else root / path
    lines = path.read_text().splitlines() if path.exists() else []
    lines = list(dict.fromkeys([*lines, *LOCAL_EXCLUDES]))

    if tracked:
        lines = [line for line in lines if line not in GENERATED_EXCLUDES]
    else:
        lines = list(dict.fromkeys([*lines, *GENERATED_EXCLUDES]))

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n")


def init(profiles: list[str], tracked: bool) -> None:
    root = Path(
        subprocess.check_output(
            ["git", "rev-parse", "--show-toplevel"], text=True
        ).strip()
    )
    profiles = profiles or detect_profiles(root)
    if not profiles:
        raise SystemExit("No profile detected; run `dev-env list` and select one.")

    module_root = Path(os.environ["RAY_DEVENV_MODULE_ROOT"])
    (root / "devenv.nix").write_text(render_nix(module_root, profiles))
    (root / "devenv.yaml").write_text(render_yaml(profiles))
    update_excludes(root, tracked)
    subprocess.run(["devenv", "allow", "--quiet"], check=True)
    print(f"Configured {root} with profiles: {' '.join(profiles)}")


def main() -> None:
    parser = argparse.ArgumentParser(prog="dev-env")
    commands = parser.add_subparsers(dest="command", required=True)
    init_parser = commands.add_parser("init", help="generate devenv files")
    init_parser.add_argument("-t", "--tracked", action="store_true")
    init_parser.add_argument("profiles", nargs="*", choices=PROFILES, metavar="PROFILE")
    commands.add_parser("list", help="list profiles")
    args = parser.parse_args()

    if args.command == "list":
        width = max(map(len, PROFILES))
        print(
            "\n".join(
                f"{name:<{width}}  {description}"
                for name, (description, _) in PROFILES.items()
            )
        )
    else:
        init(args.profiles, args.tracked)


if __name__ == "__main__":
    main()
