[shell]
# Niri has no desktop environment authentication agent of its own.
polkit_agent = true
avatar_path = "~/.config/noctalia/assets/avatar.jpg"

[shell.greeter_sync]
auto_sync = true

[shell.launcher]
categories = true
compact = true
auto_paste = true

[lockscreen]
enabled = true
fingerprint = true

[idle]
pre_action_fade_seconds = 2

[idle.behavior.lock]
timeout = 600
action = "lock"
enabled = true

[idle.behavior.screen-off]
timeout = 660
action = "screen_off"
enabled = true

[idle.behavior.suspend]
timeout = 1800
action = "lock_and_suspend"
enabled = true


[bar.default]
background_opacity = 0.88
shadow = false
padding = 10
capsule = true
capsule_fill = "#202124E6"
capsule_opacity = 1.0
capsule_padding = 6
capsule_thickness = 0.76

start = ["group:system-monitor"]
center = ["workspaces"]
end = [
  "tray",
  "privacy",
  "media",
  "network",
  "volume",
  "battery",
  "clock",
  "notifications",
  "control-center",
]

[[bar.default.capsule_group]]
id = "system-monitor"
members = ["cpu", "temp", "ram", "net-up", "net-down"]
fill = "#202124E6"

[widget.workspaces]
style = "focus_hint"
labels_only_when_occupied = true
focused_output_only = true

[widget.temp]
type = "sysmon"
stat = "cpu_temp"

[widget.net-up]
type = "sysmon"
stat = "net_tx"

[widget.net-down]
type = "sysmon"
stat = "net_rx"

[widget.clock]
tooltip_format = "{:%A, %Y-%m-%d}"

[widget.media]
hide_when_no_media = true
hide_artist = false
max_length = 180
art_size = 18
title_scroll = "always"

[widget.privacy]
hide_inactive = true

[widget.network]
show_label = false

[widget.volume]
show_label = false

[control_center]
hidden_tabs = ["weather", "screen-time"]
