RDP_USER="@username@"
RDP_PASS=""
RDP_ASKPASS="bash -c 'sed -n s/^PASSWORD=//p ~/.config/winapps/.env'"
RDP_DOMAIN=""
RDP_IP="127.0.0.1"
RDP_PORT="3389"
VM_NAME="RDPWindows"
WAFLAVOR="podman"
RDP_SCALE="180"
REMOVABLE_MEDIA="/run/media"
RDP_FLAGS="/cert:tofu /sound /microphone +home-drive /kbd:unicode"
RDP_FLAGS_NON_WINDOWS=""
RDP_FLAGS_WINDOWS="/f"
DEBUG="true"
AUTOPAUSE="off"
AUTOPAUSE_TIME="300"
FREERDP_COMMAND=""
PORT_TIMEOUT="5"
RDP_TIMEOUT="30"
APP_SCAN_TIMEOUT="60"
BOOT_TIMEOUT="120"
HIDEF="on"
